name: Petsmeet develop environment CI/CD

on:
  push:
    branches: [ "develop" ]

jobs:

  build-and-push:
  
    name: Build and push backend docker image for development environment

    runs-on: ubuntu-latest

    steps:
    - name: Login to docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build the Docker image
      uses: actions/checkout@v3
    - run: |
        cd PetMeetApp/PetMeetApp/
        echo "$PWD"
        docker build -f Dockerfile -t cubexcode/petmeet_develop:1.2 .
        docker push cubexcode/petmeet_develop:1.2

  deploy:   
    needs: [build-and-push]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: |
        echo "$PWD"
        zip -r deploy.zip . -x '*.git*'
      working-directory: PetMeetApp/PetMeetApp/

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: "eu-central-1"
        application_name: petsmeet-dev
        environment_name: Petsmeet-dev-env
        version_label: ${{ github.sha }}
        deployment_package: PetMeetApp/PetMeetApp/deploy.zip 
        
